#manifest master
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {model_name}-deployment
spec:
  selector:
    matchLabels:
<<<<<<< HEAD
      app: {model_name}-server
=======
      app: {model_names}-server
>>>>>>> 496269a1649a671ed6334ce7eeb90e9287268362
  replicas: {nodos}
  template:
    metadata:
      labels:
        app: {model_name}-server
    spec:
      containers:
      - name: {model_name}-container
        #image: gcr.io/tensorflow-serving/resnet 
        image: docker.io/{docker_user}/{model_name}:{github.sha}
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  labels:
    run: {model_name}-service
  name: {model_name}-service
spec:
  ports:
  - port: 80
    targetPort: 80
  selector:
    app: {model_name}-server
  type: LoadBalancer
